spring.application.name=config-server
server.port=8888

# Cloud Config settings
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/configurations

# Eureka registration
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}